### PR TITLE
fix: missing match for XDG_CURRENT_DESKTOP

### PR DESCRIPTION
**Pull request by 18202781743**
add DDE for Deepin Desktop.

### CODE REVIEW

**Review by BLumia — APPROVED** [review]

**Review by BLumia — APPROVED** [review]

**Comment by ComixHe** [comment]
upstream pull request: https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/111

**Comment by UTsweetyfish** [comment]
版本号不符合规范

**Comment by Zeno-sole** [comment]
@18202781743 需要使用patch形式修改，版本号后缀deepin1

**Comment by 18202781743** [comment]
https://github.com/deepin-community/xdg-utils/pull/2 合入这个吧,

**Pull request closed without merging**
